linked_list: 
	gcc -Wall -Werror -o linked_list linked_list.c

clean:
	rm -f *.o fib

# we can now run this using make in the terminal and it will run this command for us, if you want to recompile using make clean and rewrite make in the terminal 